# Generated by Django 4.0.4 on 2022-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_hometype_homemaxsulot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sotib_olngan_maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('narx', models.IntegerField()),
                ('son', models.IntegerField(default=1)),
                ('tur', models.CharField(max_length=50)),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accessmaxsulot',
            name='rasm',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='homemaxsulot',
            name='rasm',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='mobilemaxsulot',
            name='rasm',
            field=models.ImageField(upload_to='media'),
        ),
    ]
