# Generated by Django 4.0 on 2022-04-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_sotib_olngan_maxsulot_alter_accessmaxsulot_rasm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sotib_olngan_maxsulot1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('narx', models.IntegerField()),
                ('son', models.IntegerField(default=1)),
                ('tur', models.CharField(max_length=50)),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
